server:
  port: 8081

spring:
  application:
    name: huashui-auth

  main:
    allow-bean-definition-overriding: true

  config:
    import:
      - nacos:shared-mysql.yml?group=DEFAULT_GROUP&refresh-enabled=true
      - nacos:shared-springdoc.yml?group=DEFAULT_GROUP&refresh-enabled=true
      - nacos:shared-redis.yml?group=DEFAULT_GROUP&refresh-enabled=true
      - nacos:shared-token.yml?group=DEFAULT_GROUP&refresh-enabled=true



  cloud:
    nacos:
      server-addr: 127.0.0.1:18848
      username: nacos
      password: Chc23pray

      discovery:
        fail-fast: false

      config:
        refresh-enabled: true


hs:
  jdbc:
    db: huashui_rbac